# Generated by Django 5.0.2 on 2024-02-14 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icons_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='icon',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
