# Generated by Django 5.0.2 on 2024-02-17 18:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1', models.CharField(blank=True, max_length=200, null=True)),
                ('player2', models.CharField(blank=True, max_length=200, null=True)),
                ('public', models.BooleanField(blank=True, default=False, null=True)),
                ('whose_turn', models.CharField(blank=True, max_length=200, null=True)),
                ('last_turn_datetime', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_date', models.DateField(default=datetime.date.today)),
                ('started_datetime', models.DateTimeField(blank=True, default=None, null=True)),
                ('ended_datetime', models.DateTimeField(blank=True, default=None, null=True)),
                ('game_status', models.CharField(blank=True, default='not_started', max_length=200, null=True)),
                ('game_type', models.CharField(blank=True, max_length=200, null=True)),
                ('game_winner', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
