# Generated by Django 5.0.2 on 2024-02-17 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_app', '0002_piece'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='player1_color',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='player2_color',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
