# Generated by Django 5.0.2 on 2024-02-19 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_app', '0003_game_player1_color_game_player2_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='fk_game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='games_app.game'),
        ),
        migrations.AddField(
            model_name='piece',
            name='on_board',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
