# Generated by Django 5.0.2 on 2024-04-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_app', '0006_alter_game_game_winner_alter_game_whose_turn'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='moves_made',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
